### ISSUE TITLE
"Raw Input is not defined"

### ISSUE THREAD

**Issue by jensreu** [oliverb123/scrybe#1]
During setup (using setup.py) I get this little thing back
```
Traceback (most recent call last):
  File "setup.py", line 31, in <module>
    editor = raw_input("Vim, emacs or nano?: ").strip().lower()
NameError: name 'raw_input' is not defined
```
I've tried to teach myself Python lately (starting a day before so "pinch of salt" beyond this point) and this seems to be exchanged for input() in Python 3 according to wild internet searches.

EDIT: I have never felt so clever in my entire life! :D I changed it to "input()" myself in the setup.py file and now it works... I am so smart! SMRT! SMRT! 

EDIT2: .... I thought but now I cant start scrybe at all... I can choose which editor but scrybe doesn't work. Darn it!

**Comment by oliverb123** [comment]
Hey jensreu, thanks for giving scrybe a try. Right now, scrybe is written to work with python 2, which should be simply `python` in your bash shell. You're correct, the first step to changing over to python 3 is basically a search and replace of `raw_input` with `input` in all files, but you'll also need to change the bash alias but in your`~/.bashrc`. I _think_ that should be the only changes necessary, but I'd need to dig around the `os` module to be sure. If you like I can create a branch for python3 compatibility, and give it a go. Also if you could post the error messages you'r getting when you type `scrybe` or else `python scrybe.py` while in your install directory, that'd make bug squashing easier.
